[package]
name = "testws"
version = "0.1.0"
authors = ["Joshua Koo <zz85nus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"
websocket = "0.22.4"
tokio="*"
futures="*"
pcap="*"
pnet="*"
dns-lookup ="*"
serde_json = "1.0"