[package]
name = "packet_radar"
version = "0.1.0"
authors = ["Joshua Koo <zz85nus@gmail.com>", "Yang Bin Kwok <yangbin@fragnetics.com>"]
edition = "2018"

[dependencies]
websocket = "0.22"
tokio="*"
futures="*"
pcap="*"
pnet="*"
dns-lookup ="*"
serde_json = "1"
dipstick = "0.7.10"
serde = { version = "1.0", features = ["derive"] }
zerocopy = "0.2.8"
lazy_static = "1.3.0"
tls-parser = "0.9.0"
rand = "0.7.0"
pnet_macros_support = "0.22.0"
