[package]
name = "testws"
version = "0.1.0"
authors = ["Joshua Koo <zz85nus@gmail.com>", "Yang Bin Kwok <yangbin@fragnetics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.22"
tokio="*"
futures="*"
pcap="*"
pnet="*"
dns-lookup ="*"
serde_json = "1"
